### ISSUE TITLE
[New Driver] BitBucketServer

### ISSUE THREAD

**Issue by Norris1z** [laravel-shield/internals#2]
Docs: https://confluence.atlassian.com/bitbucketserver/managing-webhooks-in-bitbucket-server-938025878.html

**Comment by clarkeash** [comment]
Repo: https://github.com/laravel-shield/bitbucket-server
Invite: https://github.com/laravel-shield/bitbucket-server/invitations

I recommend using the skeleton template: https://github.com/laravel-shield/skeleton
