### ISSUE TITLE
[Submit Driver] BitBucketServer

### ISSUE THREAD

**Issue by Norris1z** [laravel-shield/internals#4]

**Comment by clarkeash** [comment]
Can you add docs here: https://github.com/laravel-shield/docs

**Comment by clarkeash** [comment]
Travis: https://travis-ci.org/laravel-shield/bitbucket-server
Scrutinizer: https://scrutinizer-ci.com/g/laravel-shield/bitbucket-server
Packagist: https://packagist.org/packages/laravel-shield/bitbucket

**Comment by Norris1z** [comment]
@clarkeash  should i add the Travis,Scrutinizer and Packagist links to a `readme.md`  ?

**Comment by clarkeash** [comment]
I would just add a link to the docs in a readme
