### ISSUE TITLE
[New Driver] GoCardless

### ISSUE THREAD

**Issue by ThibaudDauce** [laravel-shield/internals#5]
Docs: https://developer.gocardless.com/api-reference/#appendix-webhooks

**Comment by clarkeash** [comment]
Repo created here: https://github.com/laravel-shield/go-cardless
You can accept your invitation here: https://github.com/laravel-shield/go-cardless/invitations

**Comment by clarkeash** [comment]
You will need to update the namespace etc.

**Comment by clarkeash** [comment]
@ThibaudDauce any update on this?

**Comment by ThibaudDauce** [comment]
Yes… Sorry… I was really busy these last few month, I hope I will be able to build this driver but I can't tell you when. If you want to delete the repository, please do!

Thanks for your good work on Laravel Shield

**Comment by clarkeash** [comment]
Its no problem, I understand being busy 😄
